"""changes in deletes

Revision ID: 0c58d06fe70d
Revises: 161457747548
Create Date: 2025-07-16 14:01:54.858723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c58d06fe70d'
down_revision: Union[str, None] = '161457747548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('homework_reviews_submission_id_fkey'), 'homework_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'homework_reviews', 'homework_submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homework_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('homework_reviews_submission_id_fkey'), 'homework_reviews', 'homework_submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###
