"""added delete to homework

Revision ID: 3cf4cdf02e63
Revises: e73afbbd089d
Create Date: 2025-07-14 12:58:28.729090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf4cdf02e63'
down_revision: Union[str, None] = 'e73afbbd089d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_name_key'), 'courses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('courses_name_key'), 'courses', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
