"""Add name to homeworks

Revision ID: 53f373cee331
Revises: 6198e81311a8
Create Date: 2025-06-24 10:57:55.204038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f373cee331'
down_revision: Union[str, None] = '6198e81311a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('homeworks', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('homeworks', 'name')
    # ### end Alembic commands ###
