"""added description to lesson

Revision ID: 6198e81311a8
Revises: a95589a28a63
Create Date: 2025-06-23 18:08:40.482246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6198e81311a8'
down_revision: Union[str, None] = 'a95589a28a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classrooms', ['name'])
    # op.add_column('lessons', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('lessons', 'description')
    op.drop_constraint(None, 'classrooms', type_='unique')
    # ### end Alembic commands ###
