"""lesson_day

Revision ID: 7df71dbd308b
Revises: a946bbd0b68e
Create Date: 2025-07-14 16:25:44.180371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df71dbd308b'
down_revision: Union[str, None] = 'a946bbd0b68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('lessons', sa.Column('day', sa.Date(), nullable=False))
    # op.add_column('lessons', sa.Column('description', sa.Text(), nullable=True))
    # op.add_column('lessons', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_column('lessons', 'day')
    # op.drop_column('lessons', 'description')
    # op.drop_column('lessons', 'created_at')
    # ### end Alembic commands ###
