"""change reviewed_at to datetime with timezone

Revision ID: 7e46111877a2
Revises: 7df71dbd308b
Create Date: 2025-07-15 15:34:09.196862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e46111877a2'
down_revision: Union[str, None] = '7df71dbd308b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homework_reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('homework_reviews', 'reviewed_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homework_reviews', 'reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('homework_reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
