"""added delete to lessons

Revision ID: 9904446ee06a
Revises: 96475b99ea09
Create Date: 2025-07-10 19:51:29.115416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9904446ee06a'
down_revision: Union[str, None] = '96475b99ea09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('homeworks_lesson_id_fkey'), 'homeworks', type_='foreignkey')
    op.create_foreign_key(None, 'homeworks', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homeworks', type_='foreignkey')
    op.create_foreign_key(op.f('homeworks_lesson_id_fkey'), 'homeworks', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###
