"""added delete to homework

Revision ID: a28f53edce47
Revises: 9904446ee06a
Create Date: 2025-07-10 19:52:11.120056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28f53edce47'
down_revision: Union[str, None] = '9904446ee06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('homework_submissions_homework_id_fkey'), 'homework_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'homework_submissions', 'homeworks', ['homework_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homework_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('homework_submissions_homework_id_fkey'), 'homework_submissions', 'homeworks', ['homework_id'], ['id'])
    # ### end Alembic commands ###
