"""models

Revision ID: a2c631b4d086
Revises: 1d5b5840845d
Create Date: 2025-06-20 15:44:06.807116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c631b4d086'
down_revision: Union[str, None] = '1d5b5840845d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('enrollments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    # op.drop_column('enrollments', 'user_id')
    # ### end Alembic commands ###
