"""added some rows

Revision ID: a95589a28a63
Revises: a2c631b4d086
Create Date: 2025-06-23 15:21:45.124525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a95589a28a63'
down_revision: Union[str, None] = 'a2c631b4d086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('lessons', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # op.add_column('lessons', sa.Column('day', sa.Date(), nullable=False))
    op.alter_column('lessons', 'lesson_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('lessons', 'lesson_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'lesson_end',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('lessons', 'lesson_start',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # op.drop_column('lessons', 'day')
    # op.drop_column('lessons', 'created_at')
    # ### end Alembic commands ###
