"""user_description_field

Revision ID: b475d9331d6b
Revises: fb952d6b2468
Create Date: 2025-08-25 14:40:54.987182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b475d9331d6b'
down_revision: Union[str, None] = 'fb952d6b2468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'approximate_lesson_start',
               existing_type=postgresql.TIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payment_check', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('users', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.alter_column('payment_check', 'uploaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('groups', 'approximate_lesson_start',
               existing_type=postgresql.TIME(),
               server_default=sa.text("'12:00:00'::time without time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
