"""field link in lessons

Revision ID: c1cc6e61d740
Revises: d6e63adb69ae
Create Date: 2025-07-14 14:03:37.940103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cc6e61d740'
down_revision: Union[str, None] = 'd6e63adb69ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('link', db.types.HttpUrlType(length=2083), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'link')
    # ### end Alembic commands ###
