"""Add deadline to homeworks

Revision ID: c553afa7c5a9
Revises: 53f373cee331
Create Date: 2025-06-24 14:25:47.655189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c553afa7c5a9'
down_revision: Union[str, None] = '53f373cee331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('homeworks', sa.Column('deadline', sa.Date(), nullable=False))
    # op.drop_column('homeworks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('homeworks', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_column('homeworks', 'deadline')
    # ### end Alembic commands ###
