"""otp

Revision ID: e67b1f2a2aab
Revises: 74429088067c
Create Date: 2025-08-28 13:47:22.179491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67b1f2a2aab'
down_revision: Union[str, None] = '74429088067c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('purpose', sa.Enum('RESET_EMAIL', 'RESET_PASSWORD', 'UPDATE_PESONAL_DATA', name='otp_purpose'), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attemps_left', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_expires', 'otps', ['expires_at'], unique=False)
    op.create_index('uq_otp_user_purpose_active_true', 'otps', ['user_id', 'purpose'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_otp_user_purpose_active_true', table_name='otps', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_otp_expires', table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
