"""user fix

Revision ID: ed8c75e4975c
Revises: e67b1f2a2aab
Create Date: 2025-08-28 16:27:20.223354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8c75e4975c'
down_revision: Union[str, None] = 'e67b1f2a2aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groups_teacher_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_teacher_id_fkey'), 'groups', 'users', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
