"""Enum PaymentD

Revision ID: fe3a849f2c1a
Revises: fa5d6c57a7da
Create Date: 2025-07-23 13:23:31.979510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3a849f2c1a'
down_revision: Union[str, None] = 'fa5d6c57a7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_detail', sa.Column('status', sa.Enum('PAID', 'UNPAID', name='paymentdetailstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_detail', 'status')
    # ### end Alembic commands ###
