name: CI
on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

env:
  POSTGRES_DB: eureka
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  SECRET: reviro

  TEST_DB_URL: postgresql+asyncpg://postgres:postgres@localhost:5430/eureka_test

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: eureka
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Install dependencies
        run: |
          uv sync --locked --no-install-project

      - name: Create test database
        run: |
          sudo apt-get install -y postgresql-client
          psql -U postgres -h localhost -p 5430 -c 'CREATE DATABASE eureka_test;'

      - name: Run tests
        run: uv run pytest

