name: CI

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

env:
  POSTGRES_DB: eureka
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  SECRET: reviro
  TEST_DB_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/eureka_test


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready 
          --health-interval 10s --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Install dependencies
        run: |
          uv sync --locked --no-install-project

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Create test database
        run: |
          psql -U postgres -h postgres -p 5432 -c 'CREATE DATABASE eureka_test;'

      - name: Run tests
        run: uv run pytest
        env:
          DATABASE_URL: ${{ env.TEST_DB_URL }}
